// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	userapi "my-user-http-service/api/user"
	usersvc "my-user-http-service/internal/service/user"
)

// ControllerV1 is the controller for user API version 1.
type ControllerV1 struct {
	userSvc *usersvc.Service
}

func NewV1() userapi.IUserV1 {
	return &ControllerV1{
		userSvc: usersvc.New(),
	}
}
