version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./manifest/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: my-user-service:latest
    container_name: my-user-service
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql:3306
      - GF_DATABASE_NAME=test
      - GF_DATABASE_USER=root
      - GF_DATABASE_PASS=12345678

volumes:
  mysql-data:
    external:
      name: 16ddee50559782df7ff7912202b7a63a4934dfb6134534d2bf9383ef0161c26a
