// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package words

import (
	"star/api/words"
	usersLogic "star/internal/logic/users"
	wordsLogic "star/internal/logic/words"
)

type ControllerV1 struct {
	Words *wordsLogic.Words
	Users *usersLogic.Users
}

func NewV1() words.IWordsV1 {
	return &ControllerV1{
		Words: wordsLogic.New(),
		Users: usersLogic.New(),
	}
}
