// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package lark

import (
	"star/api/lark"
	larkLogic "star/internal/logic/lark"
)

type ControllerV1 struct {
	Lark *larkLogic.Lark
}

func NewV1() lark.ILarkV1 {
	return &ControllerV1{
		Lark: larkLogic.New(),
	}
}
